### PR TITLE
Place indices in the format specs

### PR DESCRIPTION
**Pull request by jmeridth**
- this allows this module to work with older versions of Python like 2.6

### CODE REVIEW

**Comment by insequent** [comment]
LGTM :snowman:

**Comment by lukaszbanasiak** [comment]
2.6 is not supported from over a year but LGTM also :)

**Comment by jmeridth** [comment]
@lukaszbanasiak thanks.  How often do you update your pypi download?

**Comment by lukaszbanasiak** [comment]
I do not have a specific road map.
It's about this patch? I can release a new version with that fix if you want.

**Comment by jmeridth** [comment]
@lukaszbanasiak that'd be awesome.  not trying to make more work for you though. :smile:  Thank you for your work on this btw.

**Comment by jmeridth** [comment]
@lukaszbanasiak thank you.  I see the new version.

**Comment by lukaszbanasiak** [comment]
@jmeridth I thank you for contribution. Check now pypi :)

**Pull request merged**
