### PR TITLE
Catch HTTPError and retry

### LINKED ISSUE #108: HTTPError 400
Hi,

I use yahoo-finance as part of Home Assistant. Have been using the module for a month now and have noticed frequent HTTPError 400 exceptions.  I have pasted a log below.  I have devised a fix for this and submit a pull request later today

``
Feb 16 06:13:59 pi2 hass[20531]: #033[31m17-02-16 06:13:59 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved#033[0m
 Feb 16 06:13:59 pi2 hass[20531]: result = coro.throw(exc)
 Feb 16 06:13:59 pi2 hass[20531]: yield from update_coro
 Feb 16 06:13:59 pi2 hass[20531]: yield from self.hass.loop.run_in_executor(None, self.update)
 Feb 16 06:13:59 pi2 hass[20531]: yield self  # This tells Task to wait for completion.
 Feb 16 06:13:59 pi2 hass[20531]: value = future.result()
 Feb 16 06:13:59 pi2 hass[20531]: raise self._exception
 Feb 16 06:13:59 pi2 hass[20531]: result = self.fn(*self.args, **self.kwargs)
 Feb 16 06:13:59 pi2 hass[20531]: self.data.update()
 Feb 16 06:13:59 pi2 hass[20531]: result = method(*args, **kwargs)
 Feb 16 06:13:59 pi2 hass[20531]: self.stock.refresh()
 Feb 16 06:13:59 pi2 hass[20531]: self.data_set = self._fetch()
 Feb 16 06:13:59 pi2 hass[20531]: data = super(Share, self)._fetch()
 Feb 16 06:13:59 pi2 hass[20531]: data = self._request(query)
 Feb 16 06:13:59 pi2 hass[20531]: response = yql.YQLQuery().execute(query)
 Feb 16 06:13:59 pi2 hass[20531]: 'env': DATATABLES_URL
 Feb 16 06:13:59 pi2 hass[20531]: return opener.open(url, data, timeout)
 Feb 16 06:13:59 pi2 hass[20531]: response = meth(req, response)
 Feb 16 06:13:59 pi2 hass[20531]: 'http', request, response, code, msg, hdrs)
 Feb 16 06:13:59 pi2 hass[20531]: return self._call_chain(*args)
 Feb 16 06:13:59 pi2 hass[20531]: result = func(*args)
 Feb 16 06:13:59 pi2 hass[20531]: raise HTTPError(req.full_url, code, msg, hdrs, fp)
Feb 16 06:13:59 pi2 hass[20531]: urllib.error.HTTPError: HTTP Error 400: Bad Request#033[0m
 Feb 16 06:47:33 pi2 hass[20531]: #033[31m17-02-16 06:47:33 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved#033[0m
``

### PR DESCRIPTION
**Pull request by timstanley1985**
Fixes #108

### CODE REVIEW

**Comment by timstanley1985** [comment]
Will fix for python 3 later today

**Comment by timstanley1985** [comment]
You are right, this isn't a proper fix, I have not debugged the root cause
of this issue and believe it may be a server side issue. I get a http 400
or 500 error for every 50-100 requests. By retrying after each failure I
have consistently made a successful request

**Comment by fschr** [comment]
@timstanley1985 Did you end up finding a solution?

**Comment by timstanley1985** [comment]
The Yahoo service has now closed. I would recommend taking a look at alpha vantage

**Comment by fschr** [comment]
I see. Thanks for the suggestion.

**Pull request closed without merging**
